name: 'Setup.Npmrc'
description: 'Create and configure .npmrc file'

branding:
  icon: file
  color: black

inputs:
  scope:
    default: ""
    required: false
  domain:
    required: true
  registry:
    required: true
  token:
    required: true
  always_auth:
    default: false
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        echo "Creating .npmrc"
        echo "//${{inputs.domain}}/:_authToken=${{inputs.token}}" > .npmrc
        echo "registry=${{inputs.registry}}" >> .npmrc

        if [ "${{inputs.scope}}" == "" ]; then
          echo "registry=${{inputs.registry}}" >> .npmrc
        else
          echo "@${{inputs.scope}}:registry=${{inputs.registry}}" >> .npmrc
        fi

        if [ "${{inputs.always_auth}}" = true ]; then
          echo "always_auth=true" >> .npmrc
        fi

        cat ./.npmrc
      shell: bash